[book]
title = "cli-template"
authors = ["rararulab"]
language = "en"
src = "src"

[output.html]
additional-css = ["theme/rara.css"]
default-theme = "light"
preferred-dark-theme = "light"
git-repository-url = "https://github.com/rararulab/cli-template"
